version: '3.7'

services:
  worker:
    build: .
    restart: always
    ports:
      - "20:20/tcp"
      - "21:21/tcp"
      - "69:69/udp"
    volumes:
      - ~/dconfig.py:/app/dconfig.py
      - ~/dracon.log:/app/dracon.log
      - ./:/app

networks:
  default:
    ipam:
      config:
        - subnet: 172.28.0.0/16
